# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c871d55b06846101deea258e112ef7eda2fce0adb1e837cd15cd28d13e4e2ed656ec6aac58dba3677e6e4fefd9bb8f05e4d6d12a778014ad53cb2d5305b33969

test:
  secret_key_base: 76142b39e08d63712f535389cc9044d3453bb66441e436079ea1714329bc7d8c6936ba2cda81f1d245db273cec0eb477cbe963b1896803aa33ce121968a1dbe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
